<?php

namespace App\DataFixtures;

use App\Entity\Record;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

/**
 * Class AppFixtures.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        foreach ($this->getData() as $datum) {
            $record = new Record();
            $record
                ->setCode($datum['code'])
                ->setName("{$datum['nom']} {$datum['post_nom']} {$datum['prenom']}")
                ->setSex($datum['sexe'])
                ->setDiplomaResult($datum['pourcentage'])
                ->setDiplomaYear($datum['annee_diplome'])
                ->setCreatedAt(new \DateTimeImmutable())
            ;

            $manager->persist($record);
        }

        $manager->flush();
    }

    private function getData(): array
    {
        return [
            [
                '﻿id' => '1',
                'nom' => 'CANSA',
                'post_nom' => 'KAYEMBE',
                'prenom' => 'AMAURY',
                'sexe' => 'M',
                'pourcentage' => '73',
                'annee_diplome' => '2021',
                'code' => '71032101020017',
            ],
            [
                '﻿id' => '2',
                'nom' => 'Dupont',
                'post_nom' => 'Martin',
                'prenom' => 'Alice',
                'sexe' => 'F',
                'pourcentage' => '70',
                'annee_diplome' => '2022',
                'code' => '71032101020097',
            ],
            [
                '﻿id' => '3',
                'nom' => 'Lefevre',
                'post_nom' => 'Moreau',
                'prenom' => 'Lucas',
                'sexe' => 'M',
                'pourcentage' => '75',
                'annee_diplome' => '2021',
                'code' => '71032101020027',
            ],
            [
                '﻿id' => '4',
                'nom' => 'Tremblay',
                'post_nom' => 'Gagnon',
                'prenom' => 'Sophie',
                'sexe' => 'F',
                'pourcentage' => '80',
                'annee_diplome' => '2023',
                'code' => '71032101020037',
            ],
            [
                '﻿id' => '5',
                'nom' => 'Smith',
                'post_nom' => 'Johnson',
                'prenom' => 'Michael',
                'sexe' => 'M',
                'pourcentage' => '85',
                'annee_diplome' => '2021',
                'code' => '71032101020047',
            ],
            [
                '﻿id' => '6',
                'nom' => 'Chen',
                'post_nom' => 'Wang',
                'prenom' => 'Li',
                'sexe' => 'F',
                'pourcentage' => '90',
                'annee_diplome' => '2022',
                'code' => '71032101020057',
            ],
            [
                '﻿id' => '7',
                'nom' => 'Garcia',
                'post_nom' => 'Martinez',
                'prenom' => 'Juan',
                'sexe' => 'M',
                'pourcentage' => '95',
                'annee_diplome' => '2023',
                'code' => '71032101020067',
            ],
            [
                '﻿id' => '8',
                'nom' => 'Kim',
                'post_nom' => 'Lee',
                'prenom' => 'Eunji',
                'sexe' => 'F',
                'pourcentage' => '78',
                'annee_diplome' => '2021',
                'code' => '71032101020077',
            ],
            [
                '﻿id' => '9',
                'nom' => 'Müller',
                'post_nom' => 'Schmidt',
                'prenom' => 'Lena',
                'sexe' => 'M',
                'pourcentage' => '82',
                'annee_diplome' => '2022',
                'code' => '71032101020087',
            ],
            [
                '﻿id' => '10',
                'nom' => 'Martin',
                'post_nom' => 'Dupont',
                'prenom' => 'John',
                'sexe' => 'M',
                'pourcentage' => '80',
                'annee_diplome' => '2023',
                'code' => '71032102020017',
            ],
            [
                '﻿id' => '11',
                'nom' => 'Moreau',
                'post_nom' => 'Lefevre',
                'prenom' => 'Emma',
                'sexe' => 'F',
                'pourcentage' => '75',
                'annee_diplome' => '2022',
                'code' => '71032102020027',
            ],
            [
                '﻿id' => '12',
                'nom' => 'Gagnon',
                'post_nom' => 'Tremblay',
                'prenom' => 'Alex',
                'sexe' => 'M',
                'pourcentage' => '85',
                'annee_diplome' => '2022',
                'code' => '71032102020037',
            ],
            [
                '﻿id' => '13',
                'nom' => 'Johnson',
                'post_nom' => 'Smith',
                'prenom' => 'Olivia',
                'sexe' => 'F',
                'pourcentage' => '88',
                'annee_diplome' => '2021',
                'code' => '71032102020047',
            ],
            [
                '﻿id' => '14',
                'nom' => 'Wang',
                'post_nom' => 'Chen',
                'prenom' => 'David',
                'sexe' => 'M',
                'pourcentage' => '92',
                'annee_diplome' => '2023',
                'code' => '71032102020057',
            ],
            [
                '﻿id' => '15',
                'nom' => 'Martinez',
                'post_nom' => 'Garcia',
                'prenom' => 'Isabella',
                'sexe' => 'F',
                'pourcentage' => '89',
                'annee_diplome' => '2021',
                'code' => '71032102020067',
            ],
            [
                '﻿id' => '16',
                'nom' => 'Lee',
                'post_nom' => 'Kim',
                'prenom' => 'Daniel',
                'sexe' => 'M',
                'pourcentage' => '79',
                'annee_diplome' => '2022',
                'code' => '71032102020077',
            ],
            [
                '﻿id' => '17',
                'nom' => 'Schmidt',
                'post_nom' => 'Müller',
                'prenom' => 'Sophia',
                'sexe' => 'F',
                'pourcentage' => '93',
                'annee_diplome' => '2023',
                'code' => '71032102020087',
            ],
            [
                '﻿id' => '18',
                'nom' => 'Miller',
                'post_nom' => 'Davis',
                'prenom' => 'Sophia',
                'sexe' => 'F',
                'pourcentage' => '80',
                'annee_diplome' => '2022',
                'code' => '71032103020017',
            ],
            [
                '﻿id' => '19',
                'nom' => 'Brown',
                'post_nom' => 'Johnson',
                'prenom' => 'Jackson',
                'sexe' => 'M',
                'pourcentage' => '75',
                'annee_diplome' => '2021',
                'code' => '71032103020027',
            ],
            [
                '﻿id' => '20',
                'nom' => 'Robinson',
                'post_nom' => 'Smith',
                'prenom' => 'Ava',
                'sexe' => 'F',
                'pourcentage' => '90',
                'annee_diplome' => '2023',
                'code' => '71032103020037',
            ],
            [
                '﻿id' => '21',
                'nom' => 'Garcia',
                'post_nom' => 'Martinez',
                'prenom' => 'Liam',
                'sexe' => 'M',
                'pourcentage' => '85',
                'annee_diplome' => '2021',
                'code' => '71032103020047',
            ],
            [
                '﻿id' => '22',
                'nom' => 'Chen',
                'post_nom' => 'Wang',
                'prenom' => 'Olivia',
                'sexe' => 'F',
                'pourcentage' => '88',
                'annee_diplome' => '2022',
                'code' => '71032103020057',
            ],
            [
                '﻿id' => '23',
                'nom' => 'Taylor',
                'post_nom' => 'Moore',
                'prenom' => 'Ethan',
                'sexe' => 'M',
                'pourcentage' => '93',
                'annee_diplome' => '2023',
                'code' => '71032103020067',
            ],
            [
                '﻿id' => '24',
                'nom' => 'Lee',
                'post_nom' => 'Kim',
                'prenom' => 'Isabella',
                'sexe' => 'F',
                'pourcentage' => '79',
                'annee_diplome' => '2021',
                'code' => '71032103020077',
            ],
            [
                '﻿id' => '25',
                'nom' => 'Jones',
                'post_nom' => 'Johnson',
                'prenom' => 'Noah',
                'sexe' => 'M',
                'pourcentage' => '82',
                'annee_diplome' => '2022',
                'code' => '71032103020087',
            ],
            [
                '﻿id' => '26',
                'nom' => 'Garcia',
                'post_nom' => 'Martinez',
                'prenom' => 'Sophia',
                'sexe' => 'F',
                'pourcentage' => '80',
                'annee_diplome' => '2022',
                'code' => '71032102020017',
            ],
            [
                '﻿id' => '27',
                'nom' => 'Lee',
                'post_nom' => 'Kim',
                'prenom' => 'Luc',
                'sexe' => 'M',
                'pourcentage' => '75',
                'annee_diplome' => '2021',
                'code' => '71032102020027',
            ],
            [
                '﻿id' => '28',
                'nom' => 'Smith',
                'post_nom' => 'Johnson',
                'prenom' => 'Emma',
                'sexe' => 'F',
                'pourcentage' => '90',
                'annee_diplome' => '2023',
                'code' => '71032102020037',
            ],
            [
                '﻿id' => '29',
                'nom' => 'Chen',
                'post_nom' => 'Wang',
                'prenom' => 'Noah',
                'sexe' => 'M',
                'pourcentage' => '85',
                'annee_diplome' => '2021',
                'code' => '71032102020047',
            ],
            [
                '﻿id' => '30',
                'nom' => 'Taylor',
                'post_nom' => 'Moore',
                'prenom' => 'Ava',
                'sexe' => 'F',
                'pourcentage' => '88',
                'annee_diplome' => '2022',
                'code' => '71032102020057',
            ],
            [
                '﻿id' => '31',
                'nom' => 'Jones',
                'post_nom' => 'Johnson',
                'prenom' => 'Ethan',
                'sexe' => 'M',
                'pourcentage' => '93',
                'annee_diplome' => '2023',
                'code' => '71032102020067',
            ],
            [
                '﻿id' => '32',
                'nom' => 'Brown',
                'post_nom' => 'Davis',
                'prenom' => 'Olivia',
                'sexe' => 'F',
                'pourcentage' => '79',
                'annee_diplome' => '2021',
                'code' => '71032102020077',
            ],
            [
                '﻿id' => '33',
                'nom' => 'Miller',
                'post_nom' => 'Smith',
                'prenom' => 'Liam',
                'sexe' => 'M',
                'pourcentage' => '82',
                'annee_diplome' => '2022',
                'code' => '71032102020087',
            ],
            [
                '﻿id' => '34',
                'nom' => 'Makamba',
                'post_nom' => 'Mugisha',
                'prenom' => 'Amina',
                'sexe' => 'F',
                'pourcentage' => '82',
                'annee_diplome' => '2022',
                'code' => '71032301020017',
            ],
            [
                '﻿id' => '35',
                'nom' => 'Ouattara',
                'post_nom' => 'Kone',
                'prenom' => 'Bakary',
                'sexe' => 'M',
                'pourcentage' => '76',
                'annee_diplome' => '2021',
                'code' => '71032301020027',
            ],
            [
                '﻿id' => '36',
                'nom' => 'Chukwu',
                'post_nom' => 'Okafor',
                'prenom' => 'Chinwe',
                'sexe' => 'F',
                'pourcentage' => '88',
                'annee_diplome' => '2023',
                'code' => '71032301020037',
            ],
            [
                '﻿id' => '37',
                'nom' => 'Adeyemi',
                'post_nom' => 'Oladeji',
                'prenom' => 'Babatunde',
                'sexe' => 'M',
                'pourcentage' => '85',
                'annee_diplome' => '2021',
                'code' => '71032301020047',
            ],
            [
                '﻿id' => '38',
                'nom' => 'Kamau',
                'post_nom' => 'Mwangi',
                'prenom' => 'Wanjiku',
                'sexe' => 'F',
                'pourcentage' => '90',
                'annee_diplome' => '2022',
                'code' => '71032301020057',
            ],
            [
                '﻿id' => '39',
                'nom' => 'Kwame',
                'post_nom' => 'Asante',
                'prenom' => 'Kwabena',
                'sexe' => 'M',
                'pourcentage' => '93',
                'annee_diplome' => '2023',
                'code' => '71032301020067',
            ],
            [
                '﻿id' => '40',
                'nom' => 'Diop',
                'post_nom' => 'Ndiaye',
                'prenom' => 'Fatou',
                'sexe' => 'F',
                'pourcentage' => '79',
                'annee_diplome' => '2021',
                'code' => '71032301020077',
            ],
            [
                '﻿id' => '41',
                'nom' => 'Nkosi',
                'post_nom' => 'Mthembu',
                'prenom' => 'Thabo',
                'sexe' => 'M',
                'pourcentage' => '87',
                'annee_diplome' => '2022',
                'code' => '71032301020087',
            ],
        ];
    }
}
